### ISSUE TITLE
Cannot run the code because of the lacking of certain components (get_masked_bce_criterion and LRDecayOptimizer)

### ISSUE THREAD

**Issue by DennisLiu94** [xuefei1/RWG_DV-Seq2Seq#1]
Hi,
    The code cannot be run because of the lacking of get_masked_bce_criterion and LRDecayOptimizer in the run_rwg.py. Any hope of fixing this?

Thank you.

**Comment by xuefei1** [comment]
Hi Dennis, thank you for reporting, will look into this ASAP.
